### ISSUE TITLE
Does this implementation include KAN?

### ISSUE THREAD

**Issue by ggggggggbahugoa** [SHI-Labs/CompactNet#1]
Hi Steven and Chuanhao,
Thanks for your pioneering work!
After downloading and running the code, I couldn't seem to find the implementation of KAN. Could you please clarify if this program includes the implementation of KAN?

Thanks!

**Comment by SiniShell1** [comment]
Hi Musk,

This implementation doesn't include KAN, since KAN has not public related codes of this task in their repository.

Best,

Chuanhao



-----Original Messages-----
From:Musk ***@***.***>
Send time:Tuesday, 06/11/2024 11:55:39
To: SHI-Labs/CompactNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SHI-Labs/CompactNet] Does this implementation include KAN? (Issue #1)






Hi Steven and Chuanhao,
Thanks for your pioneering work!
After downloading and running the code, I couldn't seem to find the implementation of KAN. Could you please clarify if this program includes the implementation of KAN?

Thanks!

**Comment by stevenwalton** [comment]
I talked with @KindXiaoming and he is hoping to release the KAN version soon. I'll keep the issue open to ensure a link is connected when that happens.

**Comment by ggggggggbahugoa** [comment]
Dear Steven and Chuanhao:

Thank you for your reply! Looking forward to your open-sourcing the code for this project! Mathematics is the mother of science, and your results demonstrate the feasibility of KAN for mathematical problems!

Additionally, I'd like to ask about Table 3 in the paper (https://arxiv.org/abs/2404.19756), where the number of parameters is listed as 200 [17,1,14]. According to equation 2.10 in the paper, the number of wb = 17x1 + 14x1; the number of ws = 17x1 + 14x1. Since G = 3, K = 3 in Table 3, we have c = (17x1 + 14x1) x 6. Therefore, the final precise number of parameters should be (17x1 + 14x1) x 8 = 248. Is this correct?

Thanks!
Best Regards

**Comment by stevenwalton** [comment]
If you have any questions about KAN please refer to [their github](https://github.com/KindXiaoming/pykan). I do not want to answers for them but I believe that is correct.

**Comment by ggggggggbahugoa** [comment]
Dear Steven:
No problem. Thanks for your reply!

**Comment by KindXiaoming** [comment]
Thank you for your patience. Here's KAN's implementation

Supervised: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Example_14_knot_supervised.ipynb
Unsupervised: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Example_15_knot_unsupervised.ipynb
